package:
  name: yams
  version:  0.0.8

source:  
  # git_url: https://github.com/ssg-aero/yams.git
  path: ../

build:
requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2019_win-64 [win]
    - ninja
    - cmake
    - python
  host:
    - python
    - python-devtools
    - pybind11
    - xtl
    - xtensor
    - xsimd
    - gbs >=0.1.9
    - tbb <2021.0        # [linux]
  run:
    - python
    - gbs
    - tbb <2021.0        # [linux]
about:
  home: http://www.ssg-aero.com
  license: LGPL3
test:
  imports:
    - pyams.yams
