package:
  name: yams
  version:  0.0.4

source:  
  # git_url: https://github.com/ssg-aero/yams.git
  path: ../

build:
requirements:
  build:
    - {{ compiler('cxx') }}
    # - {{ cdt('libx11-devel') }}         # [linux]
    # - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    # - {{ cdt('mesa-libgl-devel') }}     # [linux]
    # - {{ cdt('libxi-devel') }}          # [linux]
    - vs2019_win-64 [win]
    - ninja
    - cmake 
    # - python {{ python }}
  host:
    # - {{ cdt('libx11-devel') }}         # [linux]
    # - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    # - {{ cdt('mesa-libgl-devel') }}     # [linux]
    # - {{ cdt('libxi-devel') }}          # [linux]
    # - python {{ python }}
    - python=3.9
    - python-devtools
    - pybind11
    - xtl
    - xtensor
    - xsimd
    - gbs >=0.1.5
    - tbb <2021.0 [linux] # upgrade asap when other packages will be ready
  run:
    # - python {{ python }}
    # - pytest
    - python=3.9
    - gbs
    - tbb <2021.0 [linux] # upgrade asap when other packages will be ready
about:
  home: http://www.ssg-aero.com
  license: LGPL3
test:
  imports:
    - pyams.yams
