name: yams
channels:
  - conda-forge
  - ssg-aero
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - rapidjson
  - xtensor
  - xsimd
  - eigen
  - vtk
  - gbs
  - python=3.9
  - pybind11
  - pytest
  - gtest
  - gmock
  - nlopt
  - sel(win): vs2019_win-64